In [1]:
import numpy as np
a=np.array([1,6,2,7,4])
x=np.where(a==6)
print(x)

(array([1]),)


In [2]:
import numpy as np
a=np.array([1,6,2,7,4])
x=np.where(a==7)
print(x)

(array([3]),)


In [3]:
import numpy as np
a=np.array([1,6,2,7,6,4])
x=np.where(a%2==0)
print(x)

(array([1, 2, 4, 5]),)


In [6]:
import numpy as np
a=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(a,8,side='left')
print(x)

5


In [8]:
import numpy as np
k=np.array([2,6,5,3,7])
print(np.sort(k))

[2 3 5 6 7]


In [11]:
import numpy as np
k=np.array([[1,4,3],[5,7,9]])
print(np.sort(k))

[[1 3 4]
 [5 7 9]]


In [15]:
import numpy as np
a=np.array([31,78,69,100])
x=[False,True,False,True]
w=a[x]
print(x)
print(w)


[False, True, False, True]
[ 78 100]
