In [1]:
import numpy as np
a=np.array([10,20,30])
print("One dimensional array:",a)

One dimensional array: [10 20 30]


In [3]:
import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print("Two dimensional array:",b)

Two dimensional array: [[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Three dimensional array:",c)

Three dimensional array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
import numpy as np
d=np.zeros((3,5))
print("\n array with all zereos\n",d)


 array with all zereos
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
e=np.random.random((3,2))
print("\nrandom value\n:",e)


random value
: [[0.05304826 0.58442464]
 [0.39418929 0.34340809]
 [0.09726091 0.14164491]]


In [7]:
import numpy as np
f=np.arange(10,30,5)
print("\n sequence array \n:",f)


 sequence array 
: [10 15 20 25]


In [8]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a.reshape(4,3)
print("\n old array :\n",a)
print("\n reshaped array:\n",b)


 old array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
m=np.array([[1,2,3],[2,3,4],[5,6,7]])
a=a.flatten()
print("\n original array:\n",m)
print("\n flattened array:\n",a)


 original array:
 [[1 2 3]
 [2 3 4]
 [5 6 7]]

 flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
a=np.array([[1,2,3],[3,4,5],[6,7,8]])
print("\n No of dimensional array:\n",a.ndim)


 No of dimensional array:
 2


In [32]:
k=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("\n no of dimensional array:\n ",k.ndim)
print("\n shape of array:\n",k.shape)
print("\n elemental array:\n",k.dtype)


                            


 no of dimensional array:
  3

 shape of array:
 (2, 2, 3)

 elemental array:
 int64


In [34]:
import numpy as np
k=np.array([[1,2,3],[4,5,6],[7,8,9]])
size=len(v)
print("\n size of array:\n",k.size)


 size of array:
 9
