In [3]:
import numpy as np 
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
result=np.hstack((a,b))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [4]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
result=np.vstack((a,b))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
result=np.dstack((a,b))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [7]:
import numpy as np
a=np.array([1,2,3,4,5,6])
result=np.split(a,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [8]:
import numpy as np
a=np.array([1,2,3,4,5])
result=np.array_split(a,3)
print(result)

[array([1, 2]), array([3, 4]), array([5])]
